"""add image_url to messages

Revision ID: b206d13a04c5
Revises: 496a345c07f0
Create Date: 2026-06-20 21:47:15.455125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b206d13a04c5'
down_revision: Union[str, Sequence[str], None] = '496a345c07f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'image_url')
    # ### end Alembic commands ###
